name: Django-app workflow

on: [push]

jobs:
  Check_on_PEP8_and_pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        cd api_yamdb/
        pip install -r requirements.txt 

    - name: Test with flake8 and pytest
      run: |
        python -m flake8
        pytest
# .github/workflows/main.yml

# Тут ваши задачи тестирования и сборки образа
# ...
# Сразу после них добавьте новую задачу: деплой приложения
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: Check_on_PEP8_and_pytest
    steps:
      - name: Check out the repo
        # Проверка доступности репозитория Docker Hub для workflow
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        # Вызов сборщика контейнеров docker
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker 
        # Запуск скрипта авторизации на Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ropek745
          password: Cold1613GT
      - name: Push to Docker Hub
        # Пуш образа в Docker Hub 
        uses: docker/build-push-action@v2 
        with:
          push: true
          tags: romka745/infra_web:latest
